version: '2'

services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile
    image: stiles/rpi-docker-transmission-openvpn:latest
    container_name: transmission_container_compose
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun'
    restart: always
    ports:
      - '9091:9091'
      - '8888:8888'
      - '60001:60001'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /torrents:/data
      - ./bin:/scripts
    env_file:
      - 'common.env'
    network_mode: 'host'
    
  proxy:
    image: stiles/rpi-docker-transmission-openvpn-proxy
    container_name: proxy_container_compose
    #    links:
    # - transmission
    ports:
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - "common.env"
    network_mode: 'host'
    depends_on:
      - transmission

        #  rss:
        #    build:
        #      context: ./rss
        #      dockerfile: Dockerfile
        #    image: stiles/rpi-docker-transmission-rss-compose
        #    links:
        #      - proxy
        #    ports:
        #      - 9999:9999
        #    env_file:
        #      - "common.env"
        #    depends_on:
        #      - transmission
        #      - proxy
