FROM resin/armv7hf-ubuntu:bionic
MAINTAINER admin@roguedesigns.us

# Enable systemd
ENV INITSYSTEM on
# Your code goes here
# Update packages and install software
RUN apt-get update && apt-get -y install unrar

# Add configuration and scripts
#ADD data/ /data/


